export { default as Fiverr } from './Fiverr'
export { default as Github } from './Github'
export { default as Instagram } from './Instagram'
export { default as LinkedIn } from './LinkedIn'
export { default as Npm } from './Npm'
export { default as Paypal } from './Paypal'
export { default as Twitter } from './Twitter'
export { default as Upwork } from './Upwork'
